stateDiagram
    state "initial" as Initial
    state "dateSelected" as DateSelected
    state "startSelected" as StartSelected
    state "endSelected" as EndSelected
    state "confirmed" as Confirmed
    state "meetingSet" as MeetingSet

    [*] --> Initial
    Initial --> DateSelected : Date
    DateSelected --> Initial : Back
    DateSelected --> StartSelected : Time
    StartSelected --> DateSelected : Back
    StartSelected --> EndSelected : Time
    EndSelected --> StartSelected : Back
    EndSelected --> Confirmed : Time
    Confirmed --> EndSelected : Back
    Confirmed --> MeetingSet : 'Meeting ready'

    Initial --> Initial : Reset
    DateSelected --> Initial : Reset
    StartSelected --> Initial : Reset
    EndSelected --> Initial : Reset
    Confirmed --> Initial : Reset
    MeetingSet --> Initial : Reset
